/* eslint-disable unused-imports/no-unused-vars */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unused-vars */

import { dir } from 'i18next';
import type { Metadata } from 'next';

import './globals.css';
import { i18nConfig, type Locale } from '@/i18nConfig';

import Navbar from '../components/Navbar/Navbar';
import TranslationsProvider from '../components/TranslationsProvider';
import initTranslations from '../i18n';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

const i18namespaces = ['home'];

const RootLayout = async ({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) => {
  const { t, resources } = await initTranslations(locale, i18namespaces);
  return (
    <html dir={dir(locale)} lang={locale}>
      <body>
        <TranslationsProvider
          locale={locale}
          namespaces={i18namespaces}
          resources={resources}
        >
          <Navbar />
          {children}
        </TranslationsProvider>
      </body>
    </html>
  );
};

export default RootLayout;
